In [ ]:
%pylab inline
%config InlineBackend.figure_format = 'retina'
from ipywidgets import interact

Populating the interactive namespace from numpy and matplotlib


Turn in an image (e.g., screenshot) or PDF copy of any code that is part of your answer. Make sure all images and PDF pages are properly rotated. Make sure that all pages are clearly visible. 

Tips: Use the document scanner function on your smart phone to take better page "scans" using your camera. Make sure your screen is not shifted toward warmer colours (some devices filter blue light at night) giving it a dim and orange appearance. 

# Q1
Let $Q$ be an orthogonal $m \times m$ matrix and $\hat{R}$ be an $n\times n$ upper triangular matrix, $m>n$, such that 
$$A = Q
\begin{bmatrix}
\hat{R} \\ \mathbf{0}
\end{bmatrix}
$$

## A
Show that if the diagonal elements of $\hat{R}$ all nonzero then $A$ is full rank.

--------------------------------------------------------------

### Solution:
We can show the matrix $A$ is full rank if we can show that there is no vector $x \neq 0$ such that $Ax = 0$. We have that $Q$ is nonsingular since it is an orthogonal matrix. Hence $Qy = 0$ implies that $y=0$. So the only way that $Ax = QRx = 0$ is for $Rx = 0$. We need to show that the only way for $Rx = 0$ is for $x = 0$. In other words, we need to show that $R$ is full rank.

In class we showed that the eigenvalues of a square triangular matrix are given by the diagonal elements so that $\lambda_i = r_{ii}$ for $i=1,\ldots,m$. Since the determinant of any square matrix is the product of its eigenvalues, it follows that $$\det(\hat{R}) = \prod_{i=1}^m \lambda_i = \prod_{i=1}^m r_{ii} \neq 0,$$ 
where the last follows from the assumption that $r_{ii} \neq 0$ for all $i=1,\ldots,m$. Hence $\hat{R}$ is invertible.

Given that $\hat{R}$ is nonsingular, we have that
$$ 
\begin{bmatrix}
\hat{R} \\ \mathbf{0}
\end{bmatrix}x
=
\begin{bmatrix}
\hat{R}x \\ 0
\end{bmatrix}.
$$
Since $\hat{R}$ is nonsingular, $\hat{R}x = 0$ only if $x=0$. We conclude that $Rx = 0$ only if $x=0$.


## B
Show that if $A$ is full rank then the diagonal elements of $\hat{R}$ all nonzero.

--------------------------------------------------------------

### Solution:

We will first show that $A$ full rank implies that $R$ is full rank. If $A$ is full rank then $Ax = QRx = 0$ implies that $x=0$. It follows that $R$ must also be full rank because otherwise we would have an $x\neq 0$ such that $Rx = 0$ which would mean that $Q(Rx) = Q(0) = 0$. But by assumption, this can only be true if $x=0$ and so we have a contradiction. 

From the stucture of $R$, we must have that $\hat{R}$ is full rank and therefore $\hat{R}$ is nonsingular. Since $\hat{R}$ is nonsingular, its eigenvalues are nonzero and its diagonal elements are therefore nonzero.


## C
Let $\hat{Q}$ be $m\times n$ with orthonormal columns (so that $\hat{Q}^T\hat{Q} = I$ but $\hat{Q}$ is not invertible) such that 
$$ A = \hat{Q}\hat{R} .$$
Repeat part A and B for the above reduced QR decomposition.

--------------------------------------------------------------

### Solution
An orthogonal matrix has orthonormal columns. Therefore, any subset of its columns forms a linearly independent set. Since $\hat{Q}$ is a portion of $Q$, its colunns are linearly independent and it follows that $\hat{Q}$ is full rank. Part A proceeds with little modification since we never used the inverse of $Q$ in the argument. We need only replace "$Q$ is nonsingular" with "$\hat{Q}$ is full rank," and the rest follows.

For part B, the exact same argument applies to $A = \hat{Q}\hat{R}$.

# Q2
Let $A\in \mathbb{R}^{m\times n}$ ($m>n$) be full rank. Let the SVD decomposition of $A$ be written as
$$ A =  
\begin{bmatrix}
\hat{U} & U_0
\end{bmatrix}
\begin{bmatrix}
\hat{\Sigma} \\ \mathbf{0}
\end{bmatrix}
V^T,
$$
where $\hat{U}$ is $m\times n$, $U_0$ is $m\times(m-n)$, $\hat{\Sigma}$ is $n\times n$, and $V$ is $n\times n$. Use the above SVD to derive a formula for the pseudo inverse of $A$ in terms of $\hat{U}$, $\hat{\Sigma}$, and $V$.

--------------------------------------------------------------

### Solution
Suppose we want to find the least squares solution to $Ax = b$. In class we showed that the least squares solution satisifies $\hat{\Sigma}V^Tx = \hat{U}^T b$. We assume that $A$ is full rank, which implies that $\hat{\Sigma}$ is nonsingular. The matrix $V^T$ is orthogonal and therefore invertible with inverse $V$. It follows that $$x = A^{\dagger}b = V\hat{\Sigma}^{-1}\hat{U}^T b.$$

# Q3
Take $m=50$, $n=12$. Use the function `linspace` to produce an array $t$ of $m$ equally spaced points between on $[0, 1]$. Using two loops (or whatever means you like), produce the $m \times n$ matrix
$$ A =
\begin{bmatrix}
1 & t_1 & t_1^2 & \cdots & t_1^{n-1} \\
1 & t_2 & t_2^2 & \cdots & t_2^{n-1} \\
\vdots & \vdots & \vdots & & \vdots \\
1 & t_m & t_m^2 & \cdots & t_m^{n-1}
\end{bmatrix}.
$$
Produce an array $b = \cos(4t)$ which has $m$ elements just like $t$. This can be done with the command `b = cos(4*t)`. Calculate the least squares solution $x$ to the equation $Ax = b$ using three different methods:

  1. The normal equations using the function `cholesky`
  2. The QR decomposition using the function `qr`
  3. The SVD decomposition using the function `svd`
  
You may want to look at the help documentation for each of these functions (e.g., by using the command `help(cholesky)`). You will also want to use examples from the Week 9 Jupyter notebook, where you will find two functions: `backward_substitution` and `forward_substitution`. Copy these two functions into your homework notebook and use them to solve upper and lower triangular systems. 

These calculations above will produce three lists of twelve coefficients. In each list, shade with red pen the digits that appear to be wrong (affected by rounding error). Comment on what differences you observe. Do the normal equations exhibit instability? 

In [ ]:
def backward_substitution(U, b):
    """Upper triangular matrix `U` and right hand side vector `b`. 
    Note that `U` must be square and `U` & `b` must have compatable shape."""
    b = array(b)
    assert b.size > 1
    assert b.ndim == 1 or b.ndim == 2
    n = b.size
    assert all(diag(U) != 0), 'the diagonal elements of U must be nonzero'
    assert U.ndim == 2
    assert all(array(U.shape) == n), 'the matrix U must be square and must have same number of rows as b'
    n = b.size
    x = ones_like(b)
    for k in arange(n)[::-1]: ## iterate in reverse order
        q = 0.
        for j in arange(k+1, n):
            q = q + U[k, j]*x[j]
        x[k] = (b[k] - q)/U[k, k]
    return x
def forward_substitution(L, b):
    """Lower triangular matrix `L` and right hand side vector `b`. 
    Note that `L` must be square and `L` & `b` must have compatable shape."""
    b = array(b)
    assert b.size > 1
    assert b.ndim == 1 or b.ndim == 2
    n = b.size
    assert all(diag(L) != 0), 'the diagonal elements of L must be nonzero'
    assert L.ndim == 2
    assert all(array(L.shape) == n), 'the matrix L must be square and must have same number of rows as b'
    x = ones_like(b)
    for k in arange(n):
        q = 0.
        for j in arange(k):
            q = q + L[k, j]*x[j]
        x[k] = (b[k] - q)/L[k, k]
    return x

m = 50
n = 12
t = linspace(0, 1, m)
b = cos(4*t)
A = zeros((m, n))
for j in arange(n):
    A[:, j] = t**j
print('condition number of A:', cond(A))

condition number of A: 117177656.23888141


In [ ]:
## Normal equations via Cholesky

M = A.T@A
L = cholesky(M)
R = L.T
y = forward_substitution(R.T, A.T@b)
x1 = backward_substitution(R, y)

In [ ]:
## QR factorization via Householder
Qhat, Rhat = qr(A, mode='reduced') 
y = Qhat.T@b
x2 = backward_substitution(Rhat, y)

In [ ]:
Uhat, sigma, Vhat_T = svd(A, full_matrices=False) ## _sigma is the vector of diagonal entries, not the matrix
Vhat = Vhat_T.T
## I use broadcasting here instead of explicitly forming the matrix Sigma_inverse
y = (Uhat.T@b)/sigma ## this is equivalent to solving Sigma_hat*y = Uhat.T*b
x3 = Vhat@y

In [ ]:
print(array([x1, x2, x3]).T)

[[ 9.99999993e-01  1.00000000e+00  1.00000000e+00]
 [ 1.90646561e-06 -4.22742718e-07 -4.22742730e-07]
 [-8.00006894e+00 -7.99998124e+00 -7.99998124e+00]
 [ 9.76383453e-04 -3.18763172e-04 -3.18763174e-04]
 [ 1.06594971e+01  1.06694308e+01  1.06694308e+01]
 [ 3.10821612e-02 -1.38202865e-02 -1.38202866e-02]
 [-5.77457183e+00 -5.64707563e+00 -5.64707563e+00]
 [ 1.58480591e-01 -7.53160178e-02 -7.53160179e-02]
 [ 1.41703732e+00  1.69360696e+00  1.69360696e+00]
 [ 2.09836344e-01  6.03211402e-03  6.03211389e-03]
 [-4.59322590e-01 -3.74241706e-01 -3.74241706e-01]
 [ 1.03407907e-01  8.80405764e-02  8.80405764e-02]]


### Comment on results:
The normal equation method for solving the least squares problem is different from the other two methods. Most elements have no digits in common with the other two solutions (a few elements have the leading digit correct and one element even has 3 matching digits). The solutions from QR and SVD agree with each other for most or all of the digits in each solution element.

The innacuracy of the normal equation solution is due to instability. The condition number is $\kappa(A) \approx 10^8$ and the angle between the right hand side $b$ and the range of $A$ is almost zero. These values are approximated below.

In [ ]:
print('kappa:', cond(A)) ## condition number
print('theta:', arccos(norm(A@x3, 2)/norm(b, 2))) ## angle
# print('theta:', arccos(norm(Uhat@Uhat.T@b, 2)/norm(b, 2))) ## angle
print('eta:', norm(A, 2)*norm(x3, 2)/norm(A@x3)) ## 

kappa: 117177656.23888141
theta: 4.2146848510894035e-08
eta: 26.469300278621997
