# PT 1

$A = U \Lambda U^{-1}$

This component is what we call Eigendecomposition. Matrix $U$ contains eigenvectors and $\Lambda$ has eigenvalues.

# PT 2

Apply a Gram-Schmidt process to the columns of matrix $A$

In particular, let

$A=\left[a_1\left|a_2\right| \cdots \mid a_n\right]$

Let $\|\cdot\|$ denote the $L 2$ norm.
The Gram-Schmidt algorithm repeatedly combines the following two steps in a particular order
- normalize a vector to have unit norm
- orthogonalize the next vector
To begin, we set $u_1=a_1$ and then normalize:
$$
u_1=a_1, \quad e_1=\frac{u_1}{\left\|u_1\right\|}
$$
We orgonalize first to compute $u_2$ and then normalize to create $e_2$ :
$$
u_2=a_2-\left(a_2 \cdot e_1\right) e_1, \quad e_2=\frac{u_2}{\left\|u_2\right\|}
$$
Can verify at home that $e_1$ is orthogonal to $e_2$ by checking that $e_1 \cdot e_2=0$.
The Gram-Schmidt procedure continues iterating.
Thus, for $k=2, \ldots, n-1$ we construct
$$
u_{k+1}=a_{k+1}-\left(a_{k+1} \cdot e_1\right) e_1-\cdots-\left(a_{k+1} \cdot e_k\right) e_k, \quad e_{k+1}=\frac{u_{k+1}}{\left\|u_{k+1}\right\|}
$$

Here $\left(a_j \cdot e_i\right)$ can be interpreted as the linear least squares regression coefficient of $a_j$ on $e_i$
- it is the inner product of $a_j$ and $e_i$ divided by the inner product of $e_i$ where $e_i \cdot e_i=1$, as normalization has assured us.
- this regression coefficient has an interpretation as being a covariance divided by a variance
It can be verified that
Thus, we have constructed the decomposision
$$
A=Q R
$$

where
$$
Q=\left[a_1\left|a_2\right| \cdots \mid a_n\right]=\left[e_1\left|e_2\right| \cdots \mid e_n\right]
$$
and
$$
R=\left[\begin{array}{cccc}
a_1 \cdot e_1 & a_2 \cdot e_1 & \cdots & a_n \cdot e_1 \\
0 & a_2 \cdot e_2 & \cdots & a_n \cdot e_2 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & a_n \cdot e_n
\end{array}\right]
$$

# Non square case

Now suppose that $A$ is an $n \times m$ matrix where $m>n$.
Then a $Q R$ decomposition is
$$
A=\left[a_1\left|a_2\right| \cdots \mid a_m\right]=\left[e_1\left|e_2\right| \cdots \mid e_n\right]\left[\begin{array}{ccccccc}
a_1 \cdot e_1 & a_2 \cdot e_1 & \cdots & a_n \cdot e_1 & a_{n+1} \cdot e_1 & \cdots & a_m \cdot e_1 \\
0 & a_2 \cdot e_2 & \cdots & a_n \cdot e_2 & a_{n+1} \cdot e_2 & \cdots & a_m \cdot e_2 \\
\vdots & \vdots & \ddots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & a_n \cdot e_n & a_{n+1} \cdot e_n & \cdots & a_m \cdot e_n
\end{array}\right]
$$
which implies that
$$
\begin{aligned}
&a_1=\left(a_1 \cdot e_1\right) e_1 \\
&a_2=\left(a_2 \cdot e_1\right) e_1+\left(a_2 \cdot e_2\right) e_2 \\
&\vdots \vdots \\
&a_n=\left(a_n \cdot e_1\right) e_1+\left(a_n \cdot e_2\right) e_2+\cdots+\left(a_n \cdot e_n\right) e_n \\
&a_{n+1}=\left(a_{n+1} \cdot e_1\right) e_1+\left(a_{n+1} \cdot e_2\right) e_2+\cdots+\left(a_{n+1} \cdot e_n\right) e_n \\
&\vdots \vdots \\
&a_m=\left(a_m \cdot e_1\right) e_1+\left(a_m \cdot e_2\right) e_2+\cdots+\left(a_m \cdot e_n\right) e_n \\
&
\end{aligned}
$$

In [ ]:
import numpy as np
from scipy.linalg import qr


In [ ]:
def QR_decomposition(A):
  n,m = A.shape
  Q = np.empty((n,n)) #output
  u = np.empty((n,n)) # aux
  u[:,0] = A[:,0]
  Q[:,0] = u[:,0]/np.linalg.norm(u[:,0])
  for i in range(1,n):
    u[:,i] = A[:,i]
    for j in range(i):
      u[:,i] = u[:,i] - (A[:,i] @ Q[:,j]) * Q[:,j] 
    Q[:,i] = u[:,i]/(np.linalg.norm(u[:,i]))
  R = np.zeros((n,m))
  for i in range(n):
    for j in range(i,m):
      R[i,j] = A[:,j] @ Q[:,i]
  return Q,R

In [ ]:
# get all signs of matrix A
def diag_sign(A):
  D = np.diag(np.sign(np.diag(A)))
  return D

In [ ]:
# imposing main diag of Q pos've
# need to adjust col's in Q and rows in R

def adjust_sign(Q,R):
  D = diag_sign(Q)
  Q[:,:] = Q @ D
  R[:,:] = D @ R

  return Q, R

In [ ]:
A = np.array([[1.0, 1.0, 0.0],[1.0, 0.0, 1.0],[0.0, 1.0, 1.0]])

In [ ]:
A

array([[1., 1., 0.],
       [1., 0., 1.],
       [0., 1., 1.]])

In [ ]:
Q, R = adjust_sign(*QR_decomposition(A))

In [ ]:
Q

array([[ 0.70710678, -0.40824829, -0.57735027],
       [ 0.70710678,  0.40824829,  0.57735027],
       [ 0.        , -0.81649658,  0.57735027]])

In [ ]:
R

array([[ 1.41421356,  0.70710678,  0.70710678],
       [ 0.        , -1.22474487, -0.40824829],
       [ 0.        ,  0.        ,  1.15470054]])

In [ ]:
Q_sp, R_sp = adjust_sign(*qr(A))

In [ ]:
Q_sp-Q
R_sp - R

array([[ 2.22044605e-16, -2.22044605e-16,  0.00000000e+00],
       [ 0.00000000e+00,  4.44089210e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [ ]:
def sum(a,b):
  return a+b

vals = (1,2)

sum(vals) 

TypeError: ignored

In [ ]:
sum(*vals)

3

In [ ]:
def QR_eigeinvalues(A, tol = 1e-10, maxiter = 1000):

  A_old = np.copy(A)
  A_new = np.copy(A)

  diff = np.inf
  ctr = 0
  while(diff > tol) and (ctr < maxiter):

    A_old[:,:] = A_new
    Q,R = QR_decomposition(A_old)

    A_new[:,:] = R @ Q
    diff = np.abs(A_new - A_old).max()

    ctr += 1

  eigvals = np.diag(A_new)

  return eigvals

In [ ]:
A = np.random.random((3,3))

In [ ]:
A

array([[0.05121208, 0.51564461, 0.63763958],
       [0.37514248, 0.18282338, 0.32877411],
       [0.77772854, 0.04514839, 0.16180153]])

In [ ]:
sorted(QR_eigeinvalues(A))

[-0.6152785677484813, -0.03336261716409522, 1.0444781771309943]

In [ ]:
sorted(np.linalg.eigvals(A))

[-0.6152785677484816, -0.033362617164092195, 1.044478177130991]

In [ ]:
# 

# $A = U\Lambda U^{-1}$

In [ ]:
M = np.array([[1, 2, 1],[0, 1, 0], [ 1, 0, 1]])

In [ ]:
M

array([[1, 2, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [ ]:
ld, U = np.linalg.eig(M)

In [ ]:
print(ld)

[2. 0. 1.]


In [ ]:
print(U)

[[ 7.07106781e-01 -7.07106781e-01  2.00093587e-17]
 [ 0.00000000e+00  0.00000000e+00  4.47213595e-01]
 [ 7.07106781e-01  7.07106781e-01 -8.94427191e-01]]


In [ ]:
U_inv = np.linalg.inv(U)

In [ ]:
U_inv

array([[ 0.70710678,  1.41421356,  0.70710678],
       [-0.70710678,  1.41421356,  0.70710678],
       [ 0.        ,  2.23606798,  0.        ]])

In [ ]:
Lambda = np.diag(ld)

In [ ]:
out = np.dot(U, np.dot(Lambda, U_inv))

In [ ]:
out

array([[ 1.00000000e+00,  2.00000000e+00,  1.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00, -9.22769578e-17,  1.00000000e+00]])