In [1]:
%pylab inline
%config InlineBackend.figure_format = 'retina'
from ipywidgets import interact

Populating the interactive namespace from numpy and matplotlib


# Test matrix

In [77]:
n = 7
A = normal(0, 1, (n, n))
around(A, 3)

array([[ 0.042, -0.037,  0.154, -1.369, -0.382,  1.043, -0.018],
       [ 0.625, -0.899,  0.572,  0.763, -0.285, -0.199,  0.38 ],
       [-0.476, -0.406, -0.67 ,  0.165, -0.268, -0.662,  0.536],
       [-0.302,  1.098,  0.151,  1.194,  1.169, -0.985,  1.471],
       [ 0.238,  0.433,  0.684,  0.93 , -2.683, -1.78 , -0.681],
       [ 0.59 , -2.474,  0.143, -2.768,  0.973,  0.651, -0.338],
       [-0.647, -0.206, -2.09 , -0.12 ,  0.939, -1.512,  0.24 ]])

# SVD

In [78]:
U, sigma, VT = svd(A)
Ak = zeros([n, n])
for j in arange(n):
    uj = U[:, j]
    vj = VT[j, :]
    Ak += sigma[j]*uj[:, None]@vj[:, None].T
    print(norm(A - Ak, 'fro'), norm(sigma[j]*uj[:, None]@vj[:, None].T, 'fro'))

5.141463243850217 4.9089336465493725
3.598783394261357 3.6719752680337456
2.3625407852062694 2.71470863207237
1.4026110221146302 1.9011263194237282
0.9074592629144854 1.069502391539236
0.28260687489302216 0.8623315302785243
1.48074467654008e-14 0.2826068748930217


# QR

In [79]:

Q, R = qr(A)
Ak = zeros([n, n])
for j in arange(n):
    qj = Q[:, j]
    rj = R[j, :]
    Ak += qj[:, None]@rj[:, None].T
    print(norm(A - Ak, 'fro'), norm(qj[:, None]@rj[:, None].T, 'fro'))

6.269923656492829 3.349676279260266
4.822693190759097 4.006691034513924
4.639897435307547 1.315188732471734
3.6432107761208012 2.8732670343932223
1.8963924009516753 3.1107363470495977
0.8493396297731177 1.695560772040956
2.9373412396009384e-15 0.8493396297731175


# Cholesky

In [80]:
R = cholesky(A.T@A)
Ak = zeros([n, n])
for j in arange(n):
    rj = R[:, j]
    Ak += rj[:, None]@rj[:, None].T
    print(norm(A.T@A - Ak, 'fro'), norm(rj[:, None]@rj[:, None].T, 'fro'))

24.570371331346216 11.220331175838894
14.70000698039827 16.053573046054254
14.257554298205397 1.7297214020206009
10.345457340959975 8.255663450930825
2.986200997280179 9.67668062085547
0.7213778067031367 2.8749263316841236
2.5182736389992033e-15 0.7213778067031361


# Example: Gaussian elimination with full pivoting
Full pivoting is not used much in practice for computing a generalized LU factorization because it is computationally expensive with little improvement in stability (Trefethen and Bau). It is, however, the basis for the 2D Chebfun package.

In [83]:
A = rand(3, 3)
A

array([[0.52046547, 0.23309428, 0.34338846],
       [0.25188255, 0.21066712, 0.76758557],
       [0.83496378, 0.11747584, 0.01051691]])

In [84]:
E0 = A
i1, j1 = unravel_index(argmax(absolute(E0)), A.shape)
i1, j1

(2, 0)

In [85]:
u1 = E0[:, j1]
v1 = E0[i1, :].T
A1 = u1[:, None]@v1[:, None].T/E0[i1, j1]
A1

array([[0.52046547, 0.07322727, 0.0065556 ],
       [0.25188255, 0.0354388 , 0.00317262],
       [0.83496378, 0.11747584, 0.01051691]])

In [86]:
E1 = E0 - A1
E1

array([[0.00000000e+00, 1.59867015e-01, 3.36832862e-01],
       [0.00000000e+00, 1.75228316e-01, 7.64412949e-01],
       [0.00000000e+00, 1.38777878e-17, 0.00000000e+00]])

In [87]:
i2, j2 = unravel_index(argmax(absolute(E1)), A.shape)
i2, j2

(1, 2)

In [88]:
u2 = E1[:, j2]
v2 = E1[i2, :].T
A2 = u2[:, None]@v2[:, None].T/E1[i2, j2]
A2

array([[0.        , 0.07721305, 0.33683286],
       [0.        , 0.17522832, 0.76441295],
       [0.        , 0.        , 0.        ]])

In [89]:
A1 + A2

array([[0.52046547, 0.15044032, 0.34338846],
       [0.25188255, 0.21066712, 0.76758557],
       [0.83496378, 0.11747584, 0.01051691]])

In [90]:
E2 = E1 - A2
E2

array([[0.00000000e+00, 8.26539645e-02, 0.00000000e+00],
       [0.00000000e+00, 2.77555756e-17, 0.00000000e+00],
       [0.00000000e+00, 1.38777878e-17, 0.00000000e+00]])

In [91]:
i3, j3 = unravel_index(argmax(absolute(E2)), A.shape)
i3, j3

(0, 1)

In [92]:
u3 = E2[:, j3]
v3 = E2[i3, :].T
A3 = u3[:, None]@v3[:, None].T/E2[i3, j3]
A3

array([[0.00000000e+00, 8.26539645e-02, 0.00000000e+00],
       [0.00000000e+00, 2.77555756e-17, 0.00000000e+00],
       [0.00000000e+00, 1.38777878e-17, 0.00000000e+00]])

In [93]:
E2 - A3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## The vectors and pivots can be used to construct the L,U,P, and Q matrices
$P$ and $Q$ are permutation matrices
$$ PAQ = LU$$
### Notice the pattern of zero entries in the vectors seen below

In [94]:
print(u1)
print(u2)
print(u3)

[0.52046547 0.25188255 0.83496378]
[0.33683286 0.76441295 0.        ]
[8.26539645e-02 2.77555756e-17 1.38777878e-17]


In [95]:
print(v1)
print(v2)
print(v3)

[0.83496378 0.11747584 0.01051691]
[0.         0.17522832 0.76441295]
[0.         0.08265396 0.        ]


In [96]:
print(norm(A1, 'fro'))
print(norm(A2, 'fro'))
print(norm(A3, 'fro'))

1.0257075599381273
0.8570007883352344
0.08265396450993387
